### ISSUE TITLE
Donation not working anymore.

### ISSUE THREAD

**Issue by helenahggj** [PianothShaveck/LLM_Playground#18]
https://paypal.me/thefiredragon95

The link is dead Daniel :( I'd really like to contribute before we take the next steps together.

**Comment by meow18838** [comment]
it should be 05, not 95

**Comment by helenahggj** [comment]
Thank you! Do you still rent your botnet?

**Comment by helenahggj** [comment]
> it should be 05, not 95

Sorry, I found it on anondrop, I didn't know it wasn't updated
